account/urls.py
# -*- coding: utf-8 -*-
# Author : hejianxin
# Time : 2021/3/30 4:19 下午
from django.urls import path
from account import views


urlpatterns = [
    path('login', views.Login.as_view(), name='login'),
    path('register', views.Register.as_view(), name='register'),
    path('logout', views.Logout.as_view(), name='logout')
]

interest/urls.py
# -*- coding: utf-8 -*-
# Author : hejianxin
# Time : 2021/3/29 2:40 下午
from django.urls import path
from interest import views


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('article', views.IndexArticle.as_view(), name='article')
]

interest_circle/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('', include(('interest.urls', 'interest'), namespace='interest')),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>{% block title %}Title{% endblock %}</title>
    <style>
        body {
        padding: 0;
        margin: 0;
        }

        .root {
            height: 50px;

        }

        .top_title {
            /*border: 1px solid red;*/
            height: 50px;
            margin: 0 160px;
        }

        .title {
            height: 50px;
            line-height: 50px;
            width: 80px;
            text-align: center;
            background: #ff7744;
            float: left;
        }

        #box{
            width: 380px;
            margin-left: 38%;
            font-family: 'Microsoft YaHei';
            font-size: 14px;
            float: left;
        }

        input{
            width: 260px;
            border: 1px solid #e2e2e2;
            height: 30px;
            float: left;
            background-repeat: no-repeat;
            background-size: 25px;
            background-position:5px center;
            margin-top: 10px;
            padding:0 0 0 30px;
        }

         #search{
            width: 78px;
            height: 32px;
            float: right;
            background: #2e2513;
            color: white;
            text-align: center;
            line-height: 32px;
            margin-top: 10px;
            cursor: pointer;
         }

         .user_unlogin {
             height: 60px;
             margin-right: 50px;
             width: 140px;
             float: right;
             line-height: 50px;
             text-align: center;

         }

         .login {
             width: 70px;
             float: left;
         }
         .regist {
             width: 70px;
             float: right;
         }

          .user_login {
             height: 60px;
             margin-right: 50px;
             width: 200px;
             float: right;
             line-height: 50px;
             text-align: center;

         }
         .user {
             width: 100px;
             float: left;
         }
         .logout {
             width: 70px;
             float: right;
         }
         .clearfix {
             clear: both;
         }

    </style>

    {% block style %}  {% endblock %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>

</head>
<body>
    <div class="root">
        <div class="top_title">
            <div class="title">
            兴趣圈子
            </div>

             <div id="box">
                <input type="search" name="search" placeholder="请输入关键字">
                <div id="search">搜索</div>
             </div>

            {% if request.user.is_authenticated %}
                <div class="user_login">
                    <div class="user">{{ request.user.username }}</div>
                    <div class="logout"><a onclick="logout()" href="#">退出</a></div>
                </div>
            {% else %}
                <div class="user_unlogin">
                    <div class="login"><a href="{% url 'account:login' %}">登陆</a></div>
                    <div class="regist"><a href="{% url 'account:register' %}">注册</a></div>
                </div>
            {% endif %}
            <div class="clearfix"></div>
        </div>

    </div>
    <script>
        function logout() {
         $.ajax({
            url: "{% url 'account:logout' %}",
            type: "GET",
            success: function (data) {
                if (data["status"] == "success"){
                    window.location.href = "{% url 'interest:index' %}"
                } else {
                    alert(data["message"])
                }

            }
        })

        }
    </script>
{% block body %} {% endblock %}
{% block script %} {% endblock %}

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}兴趣圈子{% endblock %}

{% block style %}
<style>
    .body-outer {
        margin: 20px auto;
        width: 1220px;
        height: 2000px;
    }
    .body-left {
        width: 800px;
        /*height: 500px;*/
        border-top: 1px solid #E2E3E9;
        border-left: 1px solid #E2E3E9;
        border-right: 1px solid #E2E3E9;
        float: left;

    }
    .body-right {
        width: 400px;
        border: 1px solid #E2E3E9;
        margin-left: 15px;
        height: 100%;
        float: right;
    }
    .nav-bar {
        height: 45px;
        border-bottom: 1px solid #E2E3E9;
    }
    .nav-bar ul {
        margin: 0;
        padding: 0;
    }
    .nav-bar ul li {
        /*width: 70%;*/
        margin: 0 20px 0 20px;
        text-align: center;
        width: 75px;
        line-height: 45px;
        list-style: none;
        float: left;
    }
    .nav-bar ul li p {
        padding: 0;
        margin: 0;
    }

    .nav-bar ul li a {
        text-decoration:none;
        color: black;
    }
    .nav-bar ul li a:hover {
        /*text-decoration:none;*/
        color: #2b669a;
    }
    .message {
        /*border: 1px solid black;*/
        /*height: 100px;*/

    }

    .message-info {
        /*background: yellow;*/
        width: 100%;
        height: 180px;
    }

    .message-title {
        /*background: red;*/
        height: 50px;
        line-height: 50px;
        font-size: 20px;
        padding: 0 20px;
    }
    .message-body {
        /*background: #b2dba1;*/
        height: 50px;
        line-height: 28px;
        font-size: 15px;
        padding:0 20px;
        overflow: hidden;
    }
    .message-bottom {
        height: 80px;
        width: 100%;
        line-height: 80px;
        overflow: hidden;

    }
    .support {
        height: 20px;
        margin-top: 30px;
        margin-left: 30px;
        border: 1px solid black;
        width: 50px;
        line-height: 20px;
        text-align: center;

    }
</style>
{% endblock %}

{% block body %}
<div class="body-outer">
    <div class="body-left">
        <div class="nav-bar">
            <ul style="overflow: hidden">
                <li><p><a href="#" onclick="get_hot()">热门动态</a></p></li>
                <li><p><a href="">学校动态</a></p></li>
                <li><p><a href="">关注圈子</a></p></li>
            </ul>
        </div>
        <div class="message" id="message">
            <!--<div class="message-info">-->
                <!--<div class="message-title">Python学习路线</div>-->
                <!--<div class="message-body">超融合基础架构（Hyperconverged Infrastructure）作为近几年IT基础架构领域最重要变革技术之一，已经为越来越多客户所了解。部分的企业已经将超融合架构尝试应用于各种业务场景，但由于超融合和原有（Hyperconverged Infrastructure）作为近几年IT基础架构领域最重要变革技术之一，已经为越来越多客户所了解。部分的企业已经将超（Hyperconverged Infrastructure）作为近几年IT基础架构领域最重要变革技术之一，已经为越来越多客户所了解。部分的企业已经将超融合架构尝试应用于各种业务场景，但由于超融合和原有融合架构尝试应用于各种业务场景，但由于超融合和原有架构差异较大，市场存在各种角度的观</div>-->
                <!--<div class="message-bottom">-->
                    <!--<div class="support" onclick="put_support()">赞</div>-->
                <!--</div>-->
            <!--</div>-->
        </div>
    </div>
    <div class="body-right">
    </div>
    <!--<div style="clear: both"></div>-->
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    var message = document.getElementById('message');
    // message.innerHTML = '<div>hhhh</div>'
    function get_hot() {
        $.ajax({
            url: "{% url 'interest:article' %}?keyword=hot",
            type: "GET",
            success: function (data) {
                // if (data["status"] == "success"){
                //     data.
                    // window.location.href = "{% url 'interest:index' %}"
                // } else {
                //     alert(data["message"])
                // }
                // console.log(data);
                for (var item of data.results){
                    message.innerHTML +=
                        "<div class='message-info'>" +
                            "<div class='message-title'>" + item.title + "</div>" +
                            "<div class='message-body'>" + item.body + "</div>"  +
                            "<div class='message-bottom'>" +
                                "<div class='support' onclick='put_support()'>" + "赞" + "</div>" +
                            "</div>" +
                        "</div>"
                }
            }
        })
    }
   function put_support() {
    $.ajax({
        url: "{% url 'interest:article' %}?keyword=hot",
        type: "GET",
        success: function (data) {
            // if (data["status"] == "success"){
            //     data.
                // window.location.href = "{% url 'interest:index' %}"
            // } else {
            //     alert(data["message"])
            // }
            // console.log(data);
            for (var item of data.results){
                message.innerHTML += "<div class='message-info'><div class='message-title'>" + item.title + "</div>" + "<div class='message-body'>" + item.body + "<div>"  + "<div class='message-bottom'>" + "adfas" + "</div></div>>"
            }
        }
    })
}
</script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" >
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/select2.min.js' %}"></script>


</head>

<body>

    <div id="main" style="height: 538px">
        <div id="avatar"></div>
        <div id="account">
            <div class="input-box"><p>邮  箱</p><input type="text" placeholder="Please input email" id="email"></div>
            <div class="input-box"><p>密  码</p><input type="password" placeholder="Please input password" id="password"></div>
            </div>

            <button class="login-btn" onclick="put_login()">Sign In</button>
            <div id="footer">
                <a href="#">Forget Password?</a>
            </div>
        </div>
    </div>



    <script type="text/javascript">
        var password = "";
        var email = "";
        function put_login(){
            password = $('#password').val();
            email = $('#email').val();

            $.ajax({
            url: "{% url 'account:login' %}",
            data: {
                password: password,
                email: email,
                 },
            type: "POST",
            dataType: "json",
            success: function (data) {
                // data = jQuery.parseJSON(data);  //dataType指明了返回数据为json类型，故不需要再反序列化
                if (data["status"] == "success"){
                    window.location.href = "{% url 'interest:index' %}"
                } else {
                    alert(data["message"])
                }

            }
        })
        }



          $(document).ready(function() {
            $('.js-example-basic-single').select2();
        });


    </script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" >
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/select2.min.js' %}"></script>


</head>

<body>

    <div id="main">
        <div id="avatar"></div>
        <div id="account">
            <div class="input-box"><p>用户名</p><input type="text" placeholder="Please input username" id="nick_name"></div>
            <div class="input-box"><p>密  码</p><input type="password" placeholder="Please input password" id="password"></div>
<!--            <div class="input-box"><p>手  机</p><input type="text" placeholder="Please input phone" id="phone"></div>-->
            <div class="input-box"><p>邮  箱</p><input type="email" placeholder="Please input email" id="email"></div>
            <div class="input-box"><p>学  校</p>
                <select class="input-box js-example-basic-single" name="state" id="select">
                      <option value="AL">Alabama</option>
                      <option value="WY">Wyoming</option>
                        {% for school in schools %}
                      <option value="{{ school.name }}">{{ school.name }}</option>
                        {% endfor %}

                </select>
            </div>

            <button class="login-btn" onclick="put_register()">Register</button>
<!--            <div id="footer">-->
<!--                <a href="#">Forget Password?</a>-->
<!--            </div>-->
        </div>
    </div>

    <script type="text/javascript">
        var nick_name = ""
        var password = ""
        var phone = ""
        var email = ""
        var school = ""
        function put_register(){
            nick_name = $('#nick_name').val()
            password = $('#password').val()
            // phone = $('#phone').val()
            email = $('#email').val()

            $.ajax({
                url: "{% url 'account:register' %}",
                data: {
                    nick_name: nick_name,
                    password: password,
                    email: email,
                    school: school
                     },
                type: "POST",
                dataType: "json",
                success: function (data) {
                    // data = jQuery.parseJSON(data);  //dataType指明了返回数据为json类型，故不需要再反序列化
                    if (data["status"] == "success"){
                        window.location.href = "{% url 'account:login' %}"
                    } else {
                        alert(data["message"])
                    }

                }
            })
        }

        $("#select").change(function (){
            school = $(this).val()
        })

          $(document).ready(function() {
            $('.js-example-basic-single').select2();
        });




    </script>
</body>
</html>